# Copyright (c) 2020-2021 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'

services:
  ## Define mBusWS service
  ia_mbusws:
    depends_on:
      - ia_common
    build:
      context: $PWD/../mBusWS
      dockerfile: $PWD/../mBusWS/Dockerfile
      args:
        EII_VERSION: ${EII_VERSION}
        EII_UID: ${EII_UID}
        EII_USER_NAME: ${EII_USER_NAME}
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
    read_only: true
    image: ${DOCKER_REGISTRY}sade/ia_mbusws:${EII_VERSION}
    container_name: ia_mbusws
    hostname: ia_mbusws
    restart: unless-stopped
    ipc: "none"
    environment:
      AppName: "mBusWS"
      DEV_MODE: ${DEV_MODE}
      PROFILING_MODE: ${PROFILING_MODE}
      no_proxy: ${eii_no_proxy},${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_PREFIX: ${ETCD_PREFIX}

      # MessageBus Endpoint Configuration
      CertType: "zmq,pem"
      ZMQ_RECV_HWM: "50"
      # Use IPC mode (zmq_ipc) when VideoIngestion, VideoAnalytics and Visualizer
      # based containers are running on the same host. If they are running on diff
      # host, please use TCP mode for communication.
      # Eg: Stream cfg for
      # IPC: zmq_ipc, <absolute_socket_directory_path>
      # TPC: zmq_tcp, <publisher_host>:<publisher_port>

      # For default gps usecase alone
      SubTopics: "gps/gps_results,VideoIngestion/camera1_stream_results"
      #gps_results_cfg: "zmq_tcp,127.0.0.1:65017"
      gps_results_cfg: "zmq_tcp,ia_gps:65017"
      #camera1_stream_results_cfg: "zmq_tcp,127.0.0.1:65018"
      camera1_stream_results_cfg: "zmq_tcp,ia_video_ingestion:65018"
    networks:
      - eii
    ports:
      - 35331:35331
    user: ${EII_UID}
    volumes:
      - "vol_eii_socket:${SOCKET_DIR}"
      - "vol_temp_mbusws:/var/tmp"
    secrets:
      - ca_etcd
      - etcd_mBusWS_cert
      - etcd_mBusWS_key

volumes:
  vol_temp_mbusws:
    driver: local
    driver_opts:
      type: tmpfs
      o: "size=5K"
      device: tmpfs

secrets:
  etcd_mBusWS_cert:
    file: provision/Certificates/mBusWS/mBusWS_client_certificate.pem
  etcd_mBusWS_key:
    file: provision/Certificates/mBusWS/mBusWS_client_key.pem
